"""migrate model

Revision ID: 1c284edb2025
Revises: 
Create Date: 2023-03-25 15:39:27.963669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c284edb2025'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_in__charge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('person_in__charge_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lookup_data', ['department_id'], ['id'])
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_in__charge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('person_in__charge_ibfk_1', 'lookup_data', ['department'], ['id'])
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
