"""change name in ticket logs

Revision ID: 60c3e0b695e6
Revises: 1c284edb2025
Create Date: 2023-03-26 09:29:56.845192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60c3e0b695e6'
down_revision = '1c284edb2025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department__category')
    with op.batch_alter_table('complaint__ticket__logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assign_by_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('complaint__ticket__logs_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'person_in__charge', ['assign_by_id'], ['id'])
        batch_op.drop_column('assign_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint__ticket__logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assign_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('complaint__ticket__logs_ibfk_2', 'person_in__charge', ['assign_by'], ['id'])
        batch_op.drop_column('assign_by_id')

    op.create_table('department__category',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['lookup_data.id'], name='department__category_ibfk_2'),
    sa.ForeignKeyConstraint(['department_id'], ['lookup_data.id'], name='department__category_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
