"""migrate

Revision ID: 9abb3bf69c54
Revises: 5cecf7e29928
Create Date: 2023-03-27 09:25:40.358426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abb3bf69c54'
down_revision = '5cecf7e29928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_in__charge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_member', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_in__charge', schema=None) as batch_op:
        batch_op.drop_column('num_of_member')

    # ### end Alembic commands ###
